name: install-and-phpunit

on:
  [push, pull_request]

jobs:
#  coding-style:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - uses: shivammathur/setup-php@v2
#        with:
#          php-version: '8.2'
#          coverage: none
#      - name: php-cs-fixer
#        run: |
#          wget https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v3.13.2/php-cs-fixer.phar -q
#          php php-cs-fixer.phar fix --dry-run --diff

  phpunit:
    name: PHPUnit (PHP ${{ matrix.php-version }} - Symfony ${{ matrix.symfony-version }})
    runs-on: ubuntu-latest
    env:
      SYMFONY_REQUIRE: ${{ matrix.symfony-version }}

    strategy:
      matrix:
        php-version:
          - '8.4'
        symfony-version:
          - '7.3.*'
#        include:
#          - php-version: '8.3'
#            symfony-version: '6.4.*'
#          - php-version: '8.3'
#            symfony-version: '7.1.*'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PHP with pcov
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ matrix.php-version }}

      - name: Install Symfony Flex
        run: |
          composer config --global --no-plugins allow-plugins.symfony/flex true
          composer global require --no-progress --no-scripts --no-plugins symfony/flex

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v3

      - name: Run PHPUnit
        run: vendor/bin/phpunit
